name: adb-prod

services:
  mongo:
    image: mongo:7
    container_name: adb-prod-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: advance
      MONGO_INITDB_ROOT_PASSWORD: bot
    ports:
      - "27018:27017"
